# Generated by Django 5.2.8 on 2025-11-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='csv_upload_limit',
            field=models.IntegerField(default=5),
        ),
    ]
